version: '3'
services:
    mysql:
        image: 'mysql:5.7'
        container_name: mysqldb
        ports:
            - '4000:3306'
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: password
    site:
        build: .
        container_name: webwatcher
        ports:
            - '8080:80'
        expose:
            - 80
        depends_on:
            - mysql
        volumes:
            - '.:/app'
    selenium-hub:
        image: 'selenium/hub:3.12.0-boron'
        container_name: selenium-hub
        ports:
            - '4444:4444'
    chrome:
        image: 'selenium/node-chrome:3.12.0-boron'
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
    firefox:
        image: 'selenium/node-firefox:3.12.0-boron'
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
