version: '3'
services:
    db:
        image: mysql:5.7.22
        ports:
            - 3303:3306
        command: --max_allowed_packet=32MB
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    webwatcher:
        build: .
        image: ivanstan/webwatcher
        ports:
            - 8080:80
        volumes:
            - ./var/log/apache/:/var/log/apache:cached
        environment:
            DATABASE_URL: mysql://symfony:symfony@db:3306/symfony
            PROXY_PORT_RANGE: 9091-9191
            BROWSERMOB_PROXY: http://browsermob-proxy:9090
            SELENIUM_HUB: http://selenium-hub:4444/wd/hub
    selenium-hub:
        image: selenium/hub:3.12.0-boron
        ports:
            - 4444:4444
    chrome-node:
        image: selenium/node-chrome:3.12.0-boron
        ports:
            - 5900
        expose:
            - 80
        links:
            - selenium-hub
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
    browsermob-proxy:
        image: qautomatron/docker-browsermob-proxy
        ports:
            - 9090-9191:9090-9191
        expose:
            - 9090-9191
        environment:
            - PORT_RANGE=9091-9191
        links:
            - selenium-hub
            - chrome-node
