version: '2'
services:
    db:
        image: mysql:5.7.22
        ports:
            - '3303:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    nginx:
        build: .
        ports:
            - '8080:80'
        volumes:
            - './var/log/apache/:/var/log/apache:cached'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            PROXY_PORT_RANGE: 9091-9191
            BROWSERMOB_PROXY: http://browsermob-proxy:9090
            SELENIUM_HUB: http://localhost:4444/wd/hub
            PROXY_PORT_RANGE: 9091-9191
#    selenium-hub:
#        image: 'selenium/hub:3.12.0-boron'
#        ports:
#            - '4444:4444'
#    chrome-node:
#        image: 'selenium/node-chrome:3.12.0-boron'
#        volumes:
#            - '~/webwatcher/selenium:/e2e/uploads'
#            - '~/webwatcher/selenium/tmp:/e2e/uploads/tmp'
#        ports:
#            - 5900
#        expose:
#            - 80
#        links:
#            - 'selenium-hub'
#        depends_on:
#            - selenium-hub
#        environment:
#            - HUB_HOST=selenium-hub
#            - HUB_PORT=4444
#    firefox-node:
#        image: 'selenium/node-firefox:3.12.0-boron'
#        volumes:
#            - '~/webwatcher/selenium:/e2e/uploads'
#            - '~/webwatcher/selenium/tmp:/e2e/uploads/tmp'
#        ports:
#            - '5900'
#        expose:
#            - '80'
#        links:
#            - 'selenium-hub'
#        depends_on:
#            - selenium-hub
#        environment:
#            - HUB_HOST=selenium-hub
#            - HUB_PORT=4444
#    browsermob-proxy:
#        image: qautomatron/docker-browsermob-proxy
#        ports:
#            - '9090-9191:9090-9191'
#        expose:
#            - 9090-9191
#        environment:
#            - PORT_RANGE=9091-9191
#        links:
#            - 'selenium-hub'
#            - 'firefox-node'
#            - 'chrome-node'
