monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event"]
